export const COUNTRIES = [
  { code: 'co', name: 'Colombia' },
  { code: 'ec', name: 'Ecuador' }
];

export const DEPARTMENTS = [
  { code: 'Antioquia', name: 'Antioquia' },
  { code: 'Atlántico', name: 'Atlántico' },
  { code: 'Bolívar', name: 'Bolívar' },
  { code: 'Boyacá', name: 'Boyacá' },
  { code: 'Caldas', name: 'Caldas' },
  { code: 'Cauca', name: 'Cauca' },
  { code: 'Cesar', name: 'Cesar' },
  { code: 'Córdoba', name: 'Córdoba' },
  { code: 'Cundinamarca', name: 'Cundinamarca' },
  { code: 'Chocó', name: 'Chocó' },
  { code: 'Huila', name: 'Huila' },
  { code: 'La Guajira', name: 'La Guajira' },
  { code: 'Magdalena', name: 'Magdalena' },
  { code: 'Meta', name: 'Meta' },
  { code: 'Nariño', name: 'Nariño' },
  { code: 'Norte de Santander', name: 'Norte de Santander' },
  { code: 'Quindío', name: 'Quindío' },
  { code: 'Risaralda', name: 'Risaralda' },
  { code: 'Santander', name: 'Santander' },
  { code: 'Sucre', name: 'Sucre' },
  { code: 'Tolima', name: 'Tolima' },
  { code: 'Valle del Cauca', name: 'Valle del Cauca' },
  { code: 'Arauca', name: 'Arauca' },
  { code: 'Casanare', name: 'Casanare' },
  { code: 'Putumayo', name: 'Putumayo' },
  { code: 'San Andrés y Providencia', name: 'San Andrés y Providencia' },
  { code: 'Amazonas', name: 'Amazonas' },
  { code: 'Guainía', name: 'Guainía' },
  { code: 'Guaviare', name: 'Guaviare' },
  { code: 'Vaupés', name: 'Vaupés' },
  { code: 'Vichada', name: 'Vichada' }
];

export const PROVINCES_EC = [
  { code: 'Azuay', name: 'Azuay' },
  { code: 'Bolívar', name: 'Bolívar' },
  { code: 'Cañar', name: 'Cañar' },
  { code: 'Carchi', name: 'Carchi' },
  { code: 'Chimborazo', name: 'Chimborazo' },
  { code: 'Cotopaxi', name: 'Cotopaxi' },
  { code: 'El Oro', name: 'El Oro' },
  { code: 'Esmeraldas', name: 'Esmeraldas' },
  { code: 'Galápagos', name: 'Galápagos' },
  { code: 'Guayas', name: 'Guayas' },
  { code: 'Imbabura', name: 'Imbabura' },
  { code: 'Loja', name: 'Loja' },
  { code: 'Los Ríos', name: 'Los Ríos' },
  { code: 'Manabí', name: 'Manabí' },
  { code: 'Morona Santiago', name: 'Morona Santiago' },
  { code: 'Napo', name: 'Napo' },
  { code: 'Orellana', name: 'Orellana' },
  { code: 'Pastaza', name: 'Pastaza' },
  { code: 'Pichincha', name: 'Pichincha' },
  { code: 'Santa Elena', name: 'Santa Elena' },
  { code: 'Santo Domingo de los Tsáchilas', name: 'Santo Domingo de los Tsáchilas' },
  { code: 'Sucumbíos', name: 'Sucumbíos' },
  { code: 'Tungurahua', name: 'Tungurahua' },
  { code: 'Zamora Chinchipe', name: 'Zamora Chinchipe' }
];

// Simplified list of major cities/municipalities for Nariño and Capitals
export const CITIES_CO: Record<string, string[]> = {
  'Nariño': [
    'Pasto', 'Ipiales', 'Tumaco', 'La Unión', 'Sandoná', 'Túquerres', 'Samaniego', 
    'El Charco', 'Barbacoas', 'Cumbal', 'Buesaco', 'San Lorenzo', 'La Cruz', 'Taminango'
  ],
  'Antioquia': ['Medellín', 'Bello', 'Itagüí', 'Envigado', 'Apartadó', 'Rionegro'],
  'Atlántico': ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga'],
  'Bolívar': ['Cartagena', 'Magangué', 'El Carmen de Bolívar'],
  'Boyacá': ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá'],
  'Caldas': ['Manizales', 'La Dorada', 'Chinchiná'],
  'Cauca': ['Popayán', 'Santander de Quilichao', 'El Tambo'],
  'Cesar': ['Valledupar', 'Aguachica'],
  'Córdoba': ['Montería', 'Santa Cruz de Lorica', 'Sahagún'],
  'Cundinamarca': ['Bogotá', 'Soacha', 'Fusagasugá', 'Zipaquirá', 'Girardot'],
  'Chocó': ['Quibdó'],
  'Huila': ['Neiva', 'Pitalito'],
  'La Guajira': ['Riohacha', 'Maicao'],
  'Magdalena': ['Santa Marta', 'Ciénaga'],
  'Meta': ['Villavicencio', 'Acacías'],
  'Norte de Santander': ['Cúcuta', 'Ocaña', 'Villa del Rosario'],
  'Quindío': ['Armenia', 'Calarcá'],
  'Risaralda': ['Pereira', 'Dosquebradas'],
  'Santander': ['Bucaramanga', 'Floridablanca', 'Barrancabermeja', 'Girón', 'Piedecuesta'],
  'Sucre': ['Sincelejo', 'Corozal'],
  'Tolima': ['Ibagué', 'Espinal'],
  'Valle del Cauca': ['Cali', 'Buenaventura', 'Palmira', 'Tuluá', 'Yumbo', 'Cartago', 'Jamundí', 'Buga'],
  'Arauca': ['Arauca'],
  'Casanare': ['Yopal'],
  'Putumayo': ['Mocoa', 'Puerto Asís'],
  'San Andrés y Providencia': ['San Andrés'],
  'Amazonas': ['Leticia'],
  'Guainía': ['Inírida'],
  'Guaviare': ['San José del Guaviare'],
  'Vaupés': ['Mitú'],
  'Vichada': ['Puerto Carreño']
};

export const CITIES_EC: Record<string, string[]> = {
  'Azuay': ['Cuenca', 'Gualaceo'],
  'Bolívar': ['Guaranda'],
  'Cañar': ['Azogues'],
  'Carchi': ['Tulcán'],
  'Chimborazo': ['Riobamba'],
  'Cotopaxi': ['Latacunga'],
  'El Oro': ['Machala'],
  'Esmeraldas': ['Esmeraldas'],
  'Galápagos': ['Puerto Baquerizo Moreno'],
  'Guayas': ['Guayaquil', 'Durán', 'Samborondón'],
  'Imbabura': ['Ibarra', 'Otavalo'],
  'Loja': ['Loja'],
  'Los Ríos': ['Babahoyo', 'Quevedo'],
  'Manabí': ['Portoviejo', 'Manta'],
  'Morona Santiago': ['Macas'],
  'Napo': ['Tena'],
  'Orellana': ['Puerto Francisco de Orellana'],
  'Pastaza': ['Puyo'],
  'Pichincha': ['Quito', 'Cayambe', 'Sangolquí'],
  'Santa Elena': ['Santa Elena', 'Salinas'],
  'Santo Domingo de los Tsáchilas': ['Santo Domingo'],
  'Sucumbíos': ['Nueva Loja'],
  'Tungurahua': ['Ambato', 'Baños'],
  'Zamora Chinchipe': ['Zamora']
};
